server:
  port: 8080

spring:
  application:
    name: abrs

  datasource:
    url: jdbc:postgresql://localhost:5432/abrs_db
    username: postgres
    password: nbuser
    driver-class-name: org.postgresql.Driver

  # 1. JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # Use 'update' to automatically create your User/Role tables
    open-in-view: false
    show-sql: true       # Turned on so you can see the table creation in logs
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # 2. Disable Flyway temporarily if you don't have migration scripts yet
  flyway:
    enabled: false

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG # Added to help debug JWT issues
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

application:
  security:
    jwt:
      secret-key: Zk1pM1F1aVhNQmZ0R2pXb0RrZ3dJdU9oWk1vY1Z4cW1Xb1E=
      expiration: 86400000
      refresh-expiration: 604800000
