server:
  port: ${PORT:8080} # Heroku will provide the PORT dynamically

cors:
  allowed-origins: https://abrs2026.netlify.app,http://localhost,file://,content://,capacitor://,ionic://,http://localhost:4200,http://localhost:8100
spring:
  application:
    name: abrs

  datasource:
    # Use environment variables for Heroku/Production
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/abrs_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:nbuser}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Changed to 'none' or 'validate' if you've already run your SQL script
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:Zk1pM1F1aVhNQmZ0R2pXb0RrZ3dJdU9oWk1vY1Z4cW1Xb1E=}
      expiration: 86400000 # 1 day
      refresh-expiration: 604800000 # 7 days